name: Build and Publish
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up Docker build environment
        run: |
          ./builder docker purge
          ./builder docker setup
      - name: Prepare environment
        run: |
          ./builder setup
          ./builder restoresdk
      - name: Build
        run: |
          ./builder build
