name: Build and Publish
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up Docker build environment
        run: |
          ./builder docker purge
          ./builder docker setup
      - name: Prepare environment
        env:
          EXT_DL_CACHE: "${HOME}/dlcache"
        run: |
          ./builder setup
      - name: Build
        run: |
          ./builder build
